FROM python:3.12-slim

ENV DEBIAN_FRONTEND=noninteractive

# Установка зависимостей
RUN sudo apt update
sudo apt install -y firefox-esr geckodriver \
    libgtk-3-0 libdbus-glib-1-2 libasound2 libx11-xcb1 \
    libxtst6 libnss3 libxrandr2 libxss1 libatk1.0-0 \
    libatk-bridge2.0-0 libdrm2 libgbm1 libxcomposite1 \
    libxdamage1 libxfixes3

WORKDIR /app
COPY . /app

RUN pip install -r requirements.txt

CMD ["python", "main.py"]
